In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

In [2]:
import numpy as np
import tensorflow as tf

D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [6]:
np.set_printoptions(linewidth=100, precision=4)
sess = tf.InteractiveSession()

In [7]:
num_batches = 3
num_detections = 28
num_classes = 4


In [509]:
a     = tf.Variable(tf.random_uniform([20,4], minval=0, maxval=1, dtype=tf.float32, seed=1234), name = 'var')
boxes = tf.Variable(tf.random_uniform([20,4], minval=0, maxval=128, dtype=tf.float32, seed=1234), name = 'var')
fill8 = tf.zeros([8,4], dtype = tf.float32)
init  = tf.global_variables_initializer().run()

In [511]:
rng = tf.to_float(tf.range(num_detections))
rng = tf.expand_dims(rng, axis =1)
print(' Range: ',rng.shape)
print(rng.eval())

 Range:  (28, 1)
[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]
 [11.]
 [12.]
 [13.]
 [14.]
 [15.]
 [16.]
 [17.]
 [18.]
 [19.]
 [20.]
 [21.]
 [22.]
 [23.]
 [24.]
 [25.]
 [26.]
 [27.]]


In [512]:
print(fill8.eval())
print(' Pre concatenation a.shape', tf.shape(a).eval())
print(a.eval())
a = tf.concat([a, fill8],axis =0)
print(' Post concatenation a.shape', tf.shape(a).eval())
print(a.eval())

boxes = tf.concat([boxes, fill8], axis = 0)
print(' boxxes.shape', tf.shape(boxes).eval())
print(boxes.eval())

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 Pre concatenation a.shape [20  4]
[[0.8483 0.3236 0.3067 0.0697]
 [0.9139 0.1705 0.2834 0.3563]
 [0.5416 0.0753 0.0745 0.866 ]
 [0.5591 0.0093 0.067  0.4977]
 [0.2989 0.8094 0.6585 0.4815]
 [0.1517 0.591  0.3344 0.1552]
 [0.2455 0.1395 0.9869 0.9031]
 [0.1522 0.023  0.7943 0.6682]
 [0.7623 0.9574 0.8136 0.2078]
 [0.8659 0.1014 0.2265 0.0317]
 [0.1861 0.4301 0.1205 0.2435]
 [0.3574 0.1943 0.192  0.2904]
 [0.8358 0.9281 0.8308 0.0583]
 [0.3079 0.9126 0.3954 0.7867]
 [0.3893 0.0964 0.6395 0.6672]
 [0.7801 0.5502 0.5758 0.4603]
 [0.5407 0.5492 0.2173 0.6376]
 [0.482  0.0279 0.954  0.9278]
 [0.7984 0.7105 0.8229 0.7032]
 [0.4165 0.0972 0.9167 0.4561]]
 Post concatenation a.shape [28  4]
[[0.8483 0.3236 0.3067 0.0697]
 [0.9139 0.1705 0.2834 0.3563]
 [0.5416 0.0753 0.0745 0.866 ]
 [0.5591 0.0093 0.067  0.4977]
 [0.2989 0.8094 0.6585 0.4815]
 [0.1517 0.591  0.3344 0.1552]
 

In [513]:
np.set_printoptions(linewidth=100)
clas = tf.to_float(tf.argmax(a,axis=1))
clas = tf.expand_dims(clas,axis=1)
print(' classes with highest scores:',clas.shape)
print(clas.eval())
pred = tf.reduce_max(a,axis=1, keep_dims=True)   # (32,)
print(' highest scores:',pred.shape)
# print('amax.shape ', amax.shape)
a_boxes = tf.concat([rng, pred, boxes, clas], axis=1)
print(' resulting tensor : a_boxes', a_boxes.shape)
print(a_boxes.eval())

 classes with highest scores: (28, 1)
[[0.]
 [0.]
 [3.]
 [0.]
 [1.]
 [1.]
 [2.]
 [2.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [3.]
 [0.]
 [3.]
 [2.]
 [2.]
 [2.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
 highest scores: (28, 1)
 resulting tensor : a_boxes (28, 7)
[[  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
 [  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
 [  2.       0.866   69.3192   9.6329   9.5347 110.8421   3.    ]
 [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
 [  4.       0.8094  38.2599 103.6086  84.2878  61.6374   1.    ]
 [  5.       0.591   19.4185  75.6502  42.8045  19.8604   1.    ]
 [  6.       0.9869  31.423   17.8502 126.3289 115.5957   2.    ]
 [  7.       0.7943  19.4829   2.9421 101.6725  85.5338   2.    ]
 [  8.       0.9574  97.5796 122.5435 104.1375  26.6011   1.    ]
 [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
 [ 10.       0.4301  23.823   55.0586  15.4241  31.1665   1.    ]
 [ 11.

###  Sort Tensor by class id
This is column 6

In [521]:
sort_vals, sort_indcs = tf.nn.top_k(-a_boxes[:,6], k=a_boxes.shape[0])
print(sort_vals.eval())
print(sort_indcs.eval())
print(tf.shape(a_boxes).eval(), tf.shape(sort_indcs).eval())

srtd_boxes = tf.gather(a_boxes, sort_indcs)
print(' srtd_boxes shaoe: ', tf.shape(srtd_boxes).eval())
print(srtd_boxes.eval())

## - do we really need this ? srtd_boxes[:,6] gives us the class ptrs needed 
##   for dynamic_partitioning 

uniq, cls_ptrs = tf.unique(srtd_boxes[:,6])
print(uniq.shape, cls_ptrs.shape)
print(' Unqiue class ids: ', uniq.eval())
print(' Row / class mapping: ', cls_ptrs.eval())


[-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -1. -1. -1. -1. -1. -1. -2. -2. -2. -2.
 -2. -3. -3. -3.]
[ 0  1  3  9 11 15 20 21 22 23 24 25 26 27  4  5  8 10 12 13  6  7 17 18 19  2 14 16]
[28  7] [28]
 srtd_boxes shaoe:  [28  7]
[[  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
 [  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
 [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
 [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
 [ 11.       0.3574  45.7513  24.8754  24.5708  37.1656   0.    ]
 [ 15.       0.7801  99.8521  70.4273  73.7088  58.9241   0.    ]
 [ 20.       0.       0.       0.       0.       0.       0.    ]
 [ 21.       0.       0.       0.       0.       0.       0.    ]
 [ 22.       0.       0.       0.       0.       0.       0.    ]
 [ 23.       0.       0.       0.       0.       0.       0.    ]
 [ 24.       0.       0.       0.       0.       0.       0.    ]
 [ 25.       0.       0.       0

### Dynamic Partitioning 

In [522]:
cls_ptrs = tf.to_int32(srtd_boxes[:,6])
print('shape of srtd_boxes', srtd_boxes.shape)
print('cls_ptrs         ', cls_ptrs.eval())

splitted = tf.dynamic_partition(srtd_boxes, cls_ptrs, num_classes)

print(type(splitted), ' Partitioned to ', len(splitted), 'tensors')

for spl in splitted:
    print(' ------- ')
    print(spl.eval())


shape of srtd_boxes (28, 7)
cls_ptrs          [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 3 3 3]
<class 'list'>  Partitioned to  4 tensors
 ------- 
[[  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
 [  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
 [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
 [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
 [ 11.       0.3574  45.7513  24.8754  24.5708  37.1656   0.    ]
 [ 15.       0.7801  99.8521  70.4273  73.7088  58.9241   0.    ]
 [ 20.       0.       0.       0.       0.       0.       0.    ]
 [ 21.       0.       0.       0.       0.       0.       0.    ]
 [ 22.       0.       0.       0.       0.       0.       0.    ]
 [ 23.       0.       0.       0.       0.       0.       0.    ]
 [ 24.       0.       0.       0.       0.       0.       0.    ]
 [ 25.       0.       0.       0.       0.       0.       0.    ]
 [ 26.       0.       0.       0.       0.       0. 

###  Sort again - this time by score within each class 

In [523]:
# for idx in range(len(scatter)):
for idx, ten in enumerate(splitted):
#     ten = tf.squeeze(ten)
    ten_reordered = tf.gather(ten, tf.nn.top_k(ten[:,1], k=tf.shape(ten)[0]).indices)

    #     ten = scatter[idx]
    print(' item ', idx,' shape ',ten_reordered.shape, 'shape:', tf.shape(ten_reordered).eval(),
          'rank: ', tf.rank(ten_reordered).eval())
#     print(ten_reordered.eval())
#     padding = num_detections - tf.shape(ten_reordered)[0]
#     print(' num of padding rows tt add ', padding.eval())
#     print(ten.eval())  
#     ten = tf.pad(ten_reordered,[[0,padding],[0,0]]) 
#     print(' shape after padding : ', tf.shape(ten).eval())
    print(ten_reordered.eval())
    splitted[idx] = ten_reordered
    

 item  0  shape  (?, 7) shape: [14  7] rank:  2
[[  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
 [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
 [  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
 [ 15.       0.7801  99.8521  70.4273  73.7088  58.9241   0.    ]
 [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
 [ 11.       0.3574  45.7513  24.8754  24.5708  37.1656   0.    ]
 [ 20.       0.       0.       0.       0.       0.       0.    ]
 [ 21.       0.       0.       0.       0.       0.       0.    ]
 [ 22.       0.       0.       0.       0.       0.       0.    ]
 [ 23.       0.       0.       0.       0.       0.       0.    ]
 [ 24.       0.       0.       0.       0.       0.       0.    ]
 [ 25.       0.       0.       0.       0.       0.       0.    ]
 [ 26.       0.       0.       0.       0.       0.       0.    ]
 [ 27.       0.       0.       0.       0.       0.       0.    ]]
 item  1  shape  (?, 7) sha

In [525]:
for idx, ten in enumerate(splitted):
    print(' item ', idx,' shape ',ten.shape, 'shape:', tf.shape(ten).eval(), 'rank: ', tf.rank(ten).eval())
    print(ten.eval())
 

 item  0  shape  (?, 7) shape: [14  7] rank:  2
[[  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
 [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
 [  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
 [ 15.       0.7801  99.8521  70.4273  73.7088  58.9241   0.    ]
 [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
 [ 11.       0.3574  45.7513  24.8754  24.5708  37.1656   0.    ]
 [ 20.       0.       0.       0.       0.       0.       0.    ]
 [ 21.       0.       0.       0.       0.       0.       0.    ]
 [ 22.       0.       0.       0.       0.       0.       0.    ]
 [ 23.       0.       0.       0.       0.       0.       0.    ]
 [ 24.       0.       0.       0.       0.       0.       0.    ]
 [ 25.       0.       0.       0.       0.       0.       0.    ]
 [ 26.       0.       0.       0.       0.       0.       0.    ]
 [ 27.       0.       0.       0.       0.       0.       0.    ]]
 item  1  shape  (?, 7) sha

###  Pad each individual tensor to same length and stack

After this we will have a a list of tensors consisting of NUM_CLASSES  tensors each with a shape of (num_detections x 7) 

In [526]:
for idx, ten in enumerate(splitted):
    print(' item ', idx,' shape ',ten.shape, 'shape:', tf.shape(ten).eval(), 'rank: ', tf.rank(ten).eval())
    padding = num_detections - tf.shape(ten)[0]
    print(' num of padding rows tt add ', padding.eval())
#   print(ten.eval())  
    ten = tf.pad(ten,[[0,padding],[0,0]]) 
    print(' shape after padding : ', tf.shape(ten).eval())
    print(ten.eval())
    splitted[idx] = ten
    

 item  0  shape  (?, 7) shape: [14  7] rank:  2
 num of padding rows tt add  14
 shape after padding :  [28  7]
[[  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
 [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
 [  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
 [ 15.       0.7801  99.8521  70.4273  73.7088  58.9241   0.    ]
 [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
 [ 11.       0.3574  45.7513  24.8754  24.5708  37.1656   0.    ]
 [ 20.       0.       0.       0.       0.       0.       0.    ]
 [ 21.       0.       0.       0.       0.       0.       0.    ]
 [ 22.       0.       0.       0.       0.       0.       0.    ]
 [ 23.       0.       0.       0.       0.       0.       0.    ]
 [ 24.       0.       0.       0.       0.       0.       0.    ]
 [ 25.       0.       0.       0.       0.       0.       0.    ]
 [ 26.       0.       0.       0.       0.       0.       0.    ]
 [ 27.       0.       0.      

###  Finally - stack the list of tensors into one tensor

Shape of this tensor is NUM_CLASSES x NUM_MAX_DETECTIONS x NUM_COLUMNS (7)

In [527]:
stacked = tf.stack(splitted, axis = 0)
print('shape is ', tf.shape(stacked).eval())
print(stacked.eval())

shape is  [ 4 28  7]
[[[  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
  [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
  [  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
  [ 15.       0.7801  99.8521  70.4273  73.7088  58.9241   0.    ]
  [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
  [ 11.       0.3574  45.7513  24.8754  24.5708  37.1656   0.    ]
  [ 20.       0.       0.       0.       0.       0.       0.    ]
  [ 21.       0.       0.       0.       0.       0.       0.    ]
  [ 22.       0.       0.       0.       0.       0.       0.    ]
  [ 23.       0.       0.       0.       0.       0.       0.    ]
  [ 24.       0.       0.       0.       0.       0.       0.    ]
  [ 25.       0.       0.       0.       0.       0.       0.    ]
  [ 26.       0.       0.       0.       0.       0.       0.    ]
  [ 27.       0.       0.       0.       0.       0.       0.    ]
  [  0.       0.       0.       0.       

# Manipulate 3D Tensors

In [5]:
a_3d   = tf.Variable(tf.random_uniform([3,17,4], minval=0, maxval=1  , dtype=tf.float32, seed=1234), name = 'var')
box_3d = tf.Variable(tf.random_uniform([3,23,4], minval=0, maxval=128, dtype=tf.float32, seed=1234), name = 'var')
# fill8_3d = tf.zeros([3,8,4], dtype = tf.float32)
rng_3d = tf.tile(tf.range(num_detections), [num_batches])
rng_3d = tf.to_float(tf.reshape( rng_3d  , [num_batches,-1]))
rng_3d = tf.expand_dims(rng_3d, axis =2)
print(' Range: ', rng_3d.shape)
# print(rng_3d.eval())

init = tf.global_variables_initializer().run()

 Range:  (3, 28, 1)


###  Create class score tensor
 num_batches x  num_dectections x num_classes

In [6]:
# print(fill8_3d.eval())
print(' Pre concatenation a.shape', tf.shape(a_3d).eval())
print(a_3d.eval())
padding = num_detections - tf.shape(a_3d)[1]
a_3d = tf.pad(a_3d,[[0,0],[0,padding], [0,0]])

print(' padding required for a_3d : ', padding.eval())
print(' Post concatenation a.shape', tf.shape(a_3d).eval())
print(a_3d.eval())

 Pre concatenation a.shape [ 3 17  4]
[[[0.8483 0.3236 0.3067 0.0697]
  [0.9139 0.1705 0.2834 0.3563]
  [0.5416 0.0753 0.0745 0.866 ]
  [0.5591 0.0093 0.067  0.4977]
  [0.2989 0.8094 0.6585 0.4815]
  [0.1517 0.591  0.3344 0.1552]
  [0.2455 0.1395 0.9869 0.9031]
  [0.1522 0.023  0.7943 0.6682]
  [0.7623 0.9574 0.8136 0.2078]
  [0.8659 0.1014 0.2265 0.0317]
  [0.1861 0.4301 0.1205 0.2435]
  [0.3574 0.1943 0.192  0.2904]
  [0.8358 0.9281 0.8308 0.0583]
  [0.3079 0.9126 0.3954 0.7867]
  [0.3893 0.0964 0.6395 0.6672]
  [0.7801 0.5502 0.5758 0.4603]
  [0.5407 0.5492 0.2173 0.6376]]

 [[0.482  0.0279 0.954  0.9278]
  [0.7984 0.7105 0.8229 0.7032]
  [0.4165 0.0972 0.9167 0.4561]
  [0.1692 0.3054 0.6161 0.5193]
  [0.6092 0.147  0.124  0.0996]
  [0.3477 0.3669 0.3179 0.4279]
  [0.9821 0.3264 0.8513 0.0144]
  [0.7459 0.5724 0.9563 0.6972]
  [0.1117 0.7005 0.66   0.7265]
  [0.3661 0.5429 0.7805 0.6744]
  [0.2175 0.2784 0.5751 0.1126]
  [0.9919 0.7484 0.8062 0.1836]
  [0.9662 0.0838 0.7904 0.0944]


###  Create fake bounding box tensor

num_batches x nuum_detections x 4

In [7]:
print(' Pre concatenation  boxes.shape', tf.shape(box_3d).eval())
print(box_3d.eval())
padding = num_detections - tf.shape(box_3d)[1]
box_3d = tf.pad(box_3d,[[0,0],[0,padding], [0,0]])

print(' padding required for box_3d : ', padding.eval())
print(box_3d.eval())

 Pre concatenation  boxes.shape [ 3 23  4]
[[[108.5833  41.4171  39.2576   8.9216]
  [116.9736  21.8213  36.2715  45.6026]
  [ 69.3192   9.6329   9.5347 110.8421]
  [ 71.5596   1.1958   8.5777  63.7113]
  [ 38.2599 103.6086  84.2878  61.6374]
  [ 19.4185  75.6502  42.8045  19.8604]
  [ 31.423   17.8502 126.3289 115.5957]
  [ 19.4829   2.9421 101.6725  85.5338]
  [ 97.5796 122.5435 104.1375  26.6011]
  [110.8402  12.9817  28.9916   4.0611]
  [ 23.823   55.0586  15.4241  31.1665]
  [ 45.7513  24.8754  24.5708  37.1656]
  [106.9807 118.7934 106.3466   7.4645]
  [ 39.4174 116.8137  50.6049 100.7003]
  [ 49.8244  12.3429  81.8621  85.3981]
  [ 99.8521  70.4273  73.7088  58.9241]
  [ 69.2067  70.3032  27.8131  81.6126]
  [ 61.6912   3.5655 122.1108 118.7579]
  [102.1897  90.9454 105.3337  90.0073]
  [ 53.3086  12.4369 117.3345  58.387 ]
  [ 21.658   39.0892  78.8661  66.4719]
  [ 77.9712  18.8217  15.8669  12.7541]
  [ 44.5081  46.9678  40.6923  54.7697]]

 [[125.7104  41.7822 108.9662   1.8

###   Get arg max on  class scores 
This is the class corresponding to the highest score 

In [8]:
np.set_printoptions(linewidth=100)
clas_3d = tf.to_float(tf.argmax(a_3d,axis=2))
clas_3d= tf.expand_dims(clas_3d,axis=2)
print(' classes with highest scores:', tf.shape(clas_3d).eval())
print(clas_3d.eval())


 classes with highest scores: [ 3 28  1]
[[[0.]
  [0.]
  [3.]
  [0.]
  [1.]
  [1.]
  [2.]
  [2.]
  [1.]
  [0.]
  [1.]
  [0.]
  [1.]
  [1.]
  [3.]
  [0.]
  [3.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [0.]
  [3.]
  [0.]
  [2.]
  [3.]
  [2.]
  [2.]
  [0.]
  [0.]
  [0.]
  [3.]
  [1.]
  [1.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]

 [[3.]
  [3.]
  [0.]
  [3.]
  [2.]
  [0.]
  [3.]
  [3.]
  [3.]
  [3.]
  [3.]
  [3.]
  [1.]
  [3.]
  [0.]
  [2.]
  [3.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]
  [0.]]]


###  Prediction Scores 

The the highest score for each detection (highest score amongst classes)

In [9]:
pred_3d = tf.reduce_max(a_3d,axis=2, keep_dims=True)   # (32,)
print(' highest scores:', tf.shape(pred_3d).eval())
print(' pred_3d   \n', pred_3d[1].eval())


 highest scores: [ 3 28  1]
 pred_3d   
 [[0.954 ]
 [0.8229]
 [0.9167]
 [0.6161]
 [0.6092]
 [0.4279]
 [0.9821]
 [0.9563]
 [0.7265]
 [0.7805]
 [0.5751]
 [0.9919]
 [0.9662]
 [0.9445]
 [0.8228]
 [0.7196]
 [0.7694]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]
 [0.    ]]


###  Generate tensor of score - bbox - class 

In [10]:
a_boxes_3d = tf.concat([rng_3d, pred_3d,box_3d, clas_3d], axis=2)
print(' resulting tensor : a_boxes_3d', a_boxes_3d.shape)
print(a_boxes_3d[0].eval())
print('------')
print(a_boxes_3d[1].eval())
print('------')
print(a_boxes_3d[2].eval())

 resulting tensor : a_boxes_3d (3, 28, ?)
[[  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
 [  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
 [  2.       0.866   69.3192   9.6329   9.5347 110.8421   3.    ]
 [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
 [  4.       0.8094  38.2599 103.6086  84.2878  61.6374   1.    ]
 [  5.       0.591   19.4185  75.6502  42.8045  19.8604   1.    ]
 [  6.       0.9869  31.423   17.8502 126.3289 115.5957   2.    ]
 [  7.       0.7943  19.4829   2.9421 101.6725  85.5338   2.    ]
 [  8.       0.9574  97.5796 122.5435 104.1375  26.6011   1.    ]
 [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
 [ 10.       0.4301  23.823   55.0586  15.4241  31.1665   1.    ]
 [ 11.       0.3574  45.7513  24.8754  24.5708  37.1656   0.    ]
 [ 12.       0.9281 106.9807 118.7934 106.3466   7.4645   1.    ]
 [ 13.       0.9126  39.4174 116.8137  50.6049 100.7003   1.    ]
 [ 14.       0.6672  49.8244  12.3

###  Sort each slice based on class id

In [11]:
sort_vals, sort_inds = tf.nn.top_k(-a_boxes_3d[:,:,6], k=a_boxes_3d.shape[1])

In [12]:
print(tf.shape(sort_vals).eval())
print(sort_vals.eval())
print()
print(tf.shape(sort_inds).eval())
print(sort_inds.eval())

[ 3 28]
[[-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -1. -1. -1. -1. -1. -1. -2.
  -2. -3. -3. -3.]
 [-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -1. -1. -2. -2. -2. -2. -2. -2.
  -2. -3. -3. -3.]
 [-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -1. -2. -2. -3. -3. -3. -3. -3. -3. -3.
  -3. -3. -3. -3.]]

[ 3 28]
[[ 0  1  3  9 11 15 17 18 19 20 21 22 23 24 25 26 27  4  5  8 10 12 13  6  7  2 14 16]
 [ 4  6 11 12 13 17 18 19 20 21 22 23 24 25 26 27 15 16  0  1  2  3  7  9 10  5  8 14]
 [ 2  5 14 17 18 19 20 21 22 23 24 25 26 27 12  4 15  0  1  3  6  7  8  9 10 11 13 16]]


###  Rearrange each slice based on sorted indices in "indcs"

In [14]:
np.set_printoptions(linewidth=100, precision=4)

print(' indcs shape: ',sort_inds.shape)
print(sort_inds.eval())

detection_grid, batch_grid = tf.meshgrid(tf.range(num_detections),tf.range(num_batches))
print('detection_grid', type(detection_grid), 'shape',tf.shape(detection_grid).eval())
print(detection_grid.eval())

print('batch_grid', type(batch_grid), 'shape',tf.shape(batch_grid).eval())
print(batch_grid.eval())

gather_inds = tf.stack([batch_grid , sort_inds],axis = -1)

# print('-- stack results ----')
# print('gather_inds', type(gather_inds), 'shape',tf.shape(gather_inds).eval())
# print(gather_inds.eval())

print('a_boxes_3d.shape', tf.shape(a_boxes_3d).eval())
print(a_boxes_3d.eval())
# print()

srtd_boxes = tf.gather_nd(a_boxes_3d, gather_inds)
print('-- gather_nd results ----')
print(' srtd_boxes shape : ', tf.shape(srtd_boxes).eval())
print(srtd_boxes.eval())



 indcs shape:  (3, 28)
[[ 0  1  3  9 11 15 17 18 19 20 21 22 23 24 25 26 27  4  5  8 10 12 13  6  7  2 14 16]
 [ 4  6 11 12 13 17 18 19 20 21 22 23 24 25 26 27 15 16  0  1  2  3  7  9 10  5  8 14]
 [ 2  5 14 17 18 19 20 21 22 23 24 25 26 27 12  4 15  0  1  3  6  7  8  9 10 11 13 16]]
detection_grid <class 'tensorflow.python.framework.ops.Tensor'> shape [ 3 28]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]]
batch_grid <class 'tensorflow.python.framework.ops.Tensor'> shape [ 3 28]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]]
a_boxes_3d.shape [ 3 28  7]
[[[  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
  [  1.       0.9139 116.973

###  Scatter to class layers - Loop / Dynamic Partition method

In [15]:
print('shape of srtd_boxes ', srtd_boxes.shape)
partition_inds = tf.to_int32(srtd_boxes[...,6])
print(partition_inds.eval())


batch_stack = []
for i in range(num_batches):
    
    splitted = tf.dynamic_partition(srtd_boxes[i], partition_inds[i], num_classes)

    for idx, split in enumerate(splitted):
#         print(' item ', idx,' shape ',split.shape, 'shape:', tf.shape(split).eval(), 'rank: ', tf.rank(split).eval())
        padding = num_detections - tf.shape(split)[0]
        split = tf.pad(split,[[0,padding],[0,0]]) 
#         print(' num of padding rows tt add ', padding.eval())        
#         print(' shape after padding : ', tf.shape(split).eval())
#         print(split.eval())
        splitted[idx] = split
    stacked = tf.stack(splitted, axis = 0)
    batch_stack.append(stacked)

batch_tensor = tf.stack(batch_stack, axis = 0)
print(' batch _tensor shape is ', tf.shape(batch_tensor).eval())
print(batch_tensor[0].eval())    


shape of srtd_boxes  (3, 28, ?)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 2 3 3 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 2 2 2 2 2 2 2 3 3 3]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 2 2 3 3 3 3 3 3 3 3 3 3 3]]
 batch _tensor shape is  [ 3  4 28  7]
[[[  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
  [  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
  [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
  [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
  [ 11.       0.3574  45.7513  24.8754  24.5708  37.1656   0.    ]
  [ 15.       0.7801  99.8521  70.4273  73.7088  58.9241   0.    ]
  [ 17.       0.      61.6912   3.5655 122.1108 118.7579   0.    ]
  [ 18.       0.     102.1897  90.9454 105.3337  90.0073   0.    ]
  [ 19.       0.      53.3086  12.4369 117.3345  58.387    0.    ]
  [ 20.       0.      21.658   39.0892  78.8661  66.4719   0.    ]
  [ 21.       0.      77.9712  18.8217  15.8669  12.7541   0.    ]
  [ 22.       

###  Scatter to class layers - Scatter Method (?)

In [582]:
print('shape of srtd_boxes ', tf.shape(srtd_boxes).eval())
partition_inds = tf.to_int32(srtd_boxes[0,:,6])
print('shape of partition_inds ', tf.shape(partition_inds).eval())
print(partition_inds.eval())

updates=srtd_boxes[0]
print('shape of updates ', tf.shape(updates).eval())
print(updates.eval())

print('batch_grid', type(p2), 'shape',tf.shape(batch_grid).eval())
print(batch_grid.eval())
batch_grid_0 = batch_grid[0]

scatter_inds = tf.stack([ partition_inds ,batch_grid_0 ],axis = -1)
print('scatter_inds ',tf.shape(scatter_inds).eval())
print(scatter_inds.eval())


tst = tf.scatter_nd(partition_inds, updates, [4,28,7])


# splitted = tf.dynamic_partition(srtd_boxes, partition_inds, num_classes)
# tf.constant([3,28,7])
# print(len(splitted))
# for i in splitted:
#     print(type(i), tf.shape(i).eval())
# print(type(splitted), 'num of tensors in list ', len(splitted))
# for spl in splitted:
#     print(' ------- ')
#     print(spl.eval())


shape of srtd_boxes  [ 3 28  7]
shape of partition_inds  [28]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 2 3 3 3]
shape of updates  [28  7]
[[  0.       0.8483 108.5833  41.4171  39.2576   8.9216   0.    ]
 [  1.       0.9139 116.9736  21.8213  36.2715  45.6026   0.    ]
 [  3.       0.5591  71.5596   1.1958   8.5777  63.7113   0.    ]
 [  9.       0.8659 110.8402  12.9817  28.9916   4.0611   0.    ]
 [ 11.       0.3574  45.7513  24.8754  24.5708  37.1656   0.    ]
 [ 15.       0.7801  99.8521  70.4273  73.7088  58.9241   0.    ]
 [ 17.       0.      61.6912   3.5655 122.1108 118.7579   0.    ]
 [ 18.       0.     102.1897  90.9454 105.3337  90.0073   0.    ]
 [ 19.       0.      53.3086  12.4369 117.3345  58.387    0.    ]
 [ 20.       0.      21.658   39.0892  78.8661  66.4719   0.    ]
 [ 21.       0.      77.9712  18.8217  15.8669  12.7541   0.    ]
 [ 22.       0.      44.5081  46.9678  40.6923  54.7697   0.    ]
 [ 23.       0.       0.       0.       0.       0.       0.  

ValueError: The inner -25 dimensions of output.shape=[?,?,?] must match the inner 2 dimensions of updates.shape=[28,?]: Shapes must be equal rank, but are 0 and 2 for 'ScatterNd_24' (op: 'ScatterNd') with input shapes: [28], [28,?], [3].

In [37]:
a = np.reshape(np.arange(3*4*7), (3, 4, 7))

a_t = tf.constant(a)
print('\n a_t shape ios :', a_t.get_shape())
print(a_t.eval())

a_ne = tf.not_equal(a_t,0)
print('\n a_ne shape is:', a_ne.get_shape())
print(a_ne.eval())

idx = tf.where(a_ne)
print('\n idx is :', idx.get_shape())
print(idx.eval())

a_g = tf.gather_nd(a_t, idx)
print('\n a_gather_nd is :', a_g.get_shape())
print(a_g.eval())

# Use tf.shape(a_t, out_type=tf.int64) instead of a_t.get_shape() if tensor shape is dynamic
sparse = tf.SparseTensor(idx, a_g, a_t.get_shape())
print('\n sparse tensor is : ', sparse.get_shape())
# print(sparse.eval())

dense = tf.sparse_tensor_to_dense(sparse)
print('\n Desne tensor shape is :', dense.get_shape())
print(dense.eval())
# b = sess.run(dense)

np.all(a == dense.eval())


 a_t shape ios : (3, 4, 7)
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]
  [42 43 44 45 46 47 48]
  [49 50 51 52 53 54 55]]

 [[56 57 58 59 60 61 62]
  [63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76]
  [77 78 79 80 81 82 83]]]

 a_ne shape is: (3, 4, 7)
[[[False  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True]]

 [[ True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True]]

 [[ True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True]
  [ True  True  True  True  True  True  True]]]

 idx is : (?, 3)
[[0 0 1]
 [0 0 2]
 [0 0 3]
 [0 0 4]
 [0 0 5]
 [0 0 6]
 [0 1 0]


True

In [36]:
# tf.shape(tst).eval()

In [35]:
# tst.eval()


###  Experiment for sort ordering 

In [462]:
indices = tf.constant([
            [[0,2],[0,1],[0,0]],
            [[1,2],[1,1],[1,0]],
            [[2,0],[2,1],[2,1]],
          ])
params = tf.constant( [
          [['0-00', '0-01', '0-02', '0-03'], 
           ['0-10', '0-11', '0-12', '0-13'],
           ['0-20', '0-21', '0-22', '0-23'],
           ['0-30', '0-31', '0-32', '0-33']],
    
          [['1-00', '1-01', '1-02', '1-03'], 
           ['1-10', '1-11', '1-12', '1-13'],
           ['1-20', '1-21', '1-22', '1-23'],
           ['1-30', '1-31', '1-32', '1-33']],
    
          [['2-00', '2-01', '2-02', '2-03'], 
           ['2-10', '2-11', '2-12', '2-13'],
           ['2-20', '2-21', '2-22', '2-23'],
           ['2-30', '2-31', '2-32', '2-33']]    
         ])
print(params.shape, '   ', indices.shape)
res = tf.gather_nd(params, indices)
res.eval()

(3, 4, 4)     (3, 3, 2)


array([[[b'0-20', b'0-21', b'0-22', b'0-23'],
        [b'0-10', b'0-11', b'0-12', b'0-13'],
        [b'0-00', b'0-01', b'0-02', b'0-03']],

       [[b'1-20', b'1-21', b'1-22', b'1-23'],
        [b'1-10', b'1-11', b'1-12', b'1-13'],
        [b'1-00', b'1-01', b'1-02', b'1-03']],

       [[b'2-00', b'2-01', b'2-02', b'2-03'],
        [b'2-10', b'2-11', b'2-12', b'2-13'],
        [b'2-10', b'2-11', b'2-12', b'2-13']]], dtype=object)

###  Experiment with GATHER() for splitting into classes

In [84]:
# indices = tf.constant([
#             [0,2,2],[0,1,1],[0,0,0],
#             [1,2,2],[1,1,1],[1,0,0],
#             [2,0,0],[2,1,1],[2,1,1],
#            ])
# indices = tf.constant([ [0,2],[0,1],[0,0],[1,2],[1,1],[1,0],[1,2],[1,3], [2,3]] ) # 9 x 2
indices = tf.constant([
           [
            [[0,2],[0,1],[0,0],[1,2],[2,3]],
            [[1,1],[1,0],[1,2],[1,3],[1,1]]
           ]
           ])
params = tf.constant( [
          [['0-00', '0-01', '0-02', '0-03', '0-04', '0-05', '0-06'], 
           ['0-10', '0-11', '0-12', '0-13', '0-14', '0-15', '0-16'],
           ['0-20', '0-21', '0-22', '0-23', '0-24', '0-25', '0-26'],
           ['0-30', '0-31', '0-32', '0-33', '0-34', '0-35', '0-36'],
           ['0-40', '0-41', '0-42', '0-43', '0-44', '0-45', '0-46']],
                                                          
          [['1-00', '1-01', '1-02', '1-03', '1-04', '1-05', '1-06'], 
           ['1-10', '1-11', '1-12', '1-13', '1-14', '1-15', '1-16'],
           ['1-20', '1-21', '1-22', '1-23', '1-24', '1-25', '1-26'],
           ['1-30', '1-31', '1-32', '1-33', '1-34', '1-35', '1-36'],
           ['1-40', '1-41', '1-42', '1-43', '1-44', '1-45', '1-46']],
                                                          
          [['2-00', '2-01', '2-02', '2-03', '2-04', '2-05', '2-06'], 
           ['2-10', '2-11', '2-12', '2-13', '2-14', '2-15', '2-16'],
           ['2-20', '2-21', '2-22', '2-23', '2-24', '2-25', '2-26'],
           ['2-30', '2-31', '2-32', '2-33', '2-34', '2-35', '2-36'],
           ['2-40', '2-41', '2-42', '2-43', '2-44', '2-45', '2-46']]    
         ])
print(' params sahape: ', params.shape, ' parms[:axis]', params.shape[:0], params.shape[:1], params.shape[:2], params.shape[:3])
print(' params sahape: ', params.shape, ' parms[:axis]', params.shape[0:], params.shape[1:], params.shape[2:], params.shape[3:])
print(' indices.shape  ', indices.shape)
res = tf.gather_nd(params, indices)
print('result shape   ', res.get_shape())
res.eval()

 params sahape:  (3, 5, 7)  parms[:axis] () (3,) (3, 5) (3, 5, 7)
 params sahape:  (3, 5, 7)  parms[:axis] (3, 5, 7) (5, 7) (7,) ()
 indices.shape   (1, 2, 5, 2)
result shape    (1, 2, 5, 7)


array([[[[b'0-20', b'0-21', b'0-22', b'0-23', b'0-24', b'0-25', b'0-26'],
         [b'0-10', b'0-11', b'0-12', b'0-13', b'0-14', b'0-15', b'0-16'],
         [b'0-00', b'0-01', b'0-02', b'0-03', b'0-04', b'0-05', b'0-06'],
         [b'1-20', b'1-21', b'1-22', b'1-23', b'1-24', b'1-25', b'1-26'],
         [b'2-30', b'2-31', b'2-32', b'2-33', b'2-34', b'2-35', b'2-36']],

        [[b'1-10', b'1-11', b'1-12', b'1-13', b'1-14', b'1-15', b'1-16'],
         [b'1-00', b'1-01', b'1-02', b'1-03', b'1-04', b'1-05', b'1-06'],
         [b'1-20', b'1-21', b'1-22', b'1-23', b'1-24', b'1-25', b'1-26'],
         [b'1-30', b'1-31', b'1-32', b'1-33', b'1-34', b'1-35', b'1-36'],
         [b'1-10', b'1-11', b'1-12', b'1-13', b'1-14', b'1-15', b'1-16']]]], dtype=object)

###  Experiment with SCATTER() for splitting into classes

In [126]:
del indices, updates, shape

indices =  tf.constant([
                       [[0,0], [3,0], [2,0], [1,0]]  #<--- each one corrsponds to an entry in  the updates array [row , position in resulting array]
                      ])

updates = tf.constant( [
          [[1000, 1001, 1002, 1003, 1004, 1005, 1006], 
           [1010, 1011, 1012, 1013, 1014, 1015, 1016],
           [1020, 1021, 1022, 1023, 1024, 1025, 1026],
           [1030, 1031, 1032, 1033, 1034, 1035, 1036]]
         ])                       

# zeros = tf.zeros([1,4,7])
# ref   = tf.Variable(zeros, dtype = tf.float32)
# scatt = tf.Variable(zeros, dtype = tf.float32)

shape = tf.constant([1, 4, 7])

print('indices shape ', indices.shape, indices, 'indices_shape [:0]', indices.shape[:0])
print('updates.shape ', updates.shape, updates)
print('ref     shape ', ref.get_shape(), ref)
print('scatter shape ', scatt.get_shape(), scatt)
scatt = tf.scatter_nd(indices, updates, shape)

# scatt = tf.scatter_nd_update(ref, indices, updates)
print('scatter shape is ', scatt.get_shape(), scatt)

with tf.Session() as sess1:
  print(sess1.run(scatt))

indices shape  (1, 4, 2) Tensor("Const_214:0", shape=(1, 4, 2), dtype=int32) indices_shape [:0] ()
updates.shape  (1, 4, 7) Tensor("Const_215:0", shape=(1, 4, 7), dtype=int32)
ref     shape  (1, 4, 7) <tf.Variable 'Variable_38:0' shape=(1, 4, 7) dtype=float32_ref>
scatter shape  (1, 4, 7) <tf.Variable 'Variable_39:0' shape=(1, 4, 7) dtype=float32_ref>
scatter shape is  (1, 4, 7) Tensor("ScatterNd_23:0", shape=(1, 4, 7), dtype=int32)


InvalidArgumentError: No OpKernel was registered to support Op 'ScatterNd' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]

	 [[Node: ScatterNd_14 = ScatterNd[T=DT_STRING, Tindices=DT_INT32](Const_86, Const_88, Const_89)]]

Caused by op 'ScatterNd_14', defined at:
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\kernelapp.py", line 478, in start
    self.io_loop.start()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-72-b06aa1b7a35e>", line 32, in <module>
    scatter = tf.scatter_nd(indices, updates, shape)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4378, in scatter_nd
    "ScatterNd", indices=indices, updates=updates, shape=shape, name=name)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'ScatterNd' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]

	 [[Node: ScatterNd_14 = ScatterNd[T=DT_STRING, Tindices=DT_INT32](Const_86, Const_88, Const_89)]]


In [121]:
indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([9, 10, 11, 12])
shape   = tf.constant([8])
scatter = tf.scatter_nd(indices, updates, shape)
print(scatter.eval())

[ 0 11  0 10  9  0  0 12]


In [118]:
ref = tf.Variable([1, 2, 3, 4, 5, 6, 7, 8])
indices = tf.constant([[4], [3], [1] ,[7]])
updates = tf.constant([9, 10, 11, 12])
update = tf.scatter_nd_update(ref, indices, updates)
with tf.Session() as sess1:
  print(sess1.run(update))


InvalidArgumentError: No OpKernel was registered to support Op 'ScatterNd' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]

	 [[Node: ScatterNd_14 = ScatterNd[T=DT_STRING, Tindices=DT_INT32](Const_86, Const_88, Const_89)]]

Caused by op 'ScatterNd_14', defined at:
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\kernelapp.py", line 478, in start
    self.io_loop.start()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-72-b06aa1b7a35e>", line 32, in <module>
    scatter = tf.scatter_nd(indices, updates, shape)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 4378, in scatter_nd
    "ScatterNd", indices=indices, updates=updates, shape=shape, name=name)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "D:\Program Files\Anaconda3\envs\TF_gpu\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'ScatterNd' with these attrs.  Registered devices: [CPU,GPU], Registered kernels:
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT16]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_UINT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT8]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_HALF]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_DOUBLE]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX64]; Tindices in [DT_INT64]
  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT32]
  device='GPU'; T in [DT_COMPLEX128]; Tindices in [DT_INT64]

	 [[Node: ScatterNd_14 = ScatterNd[T=DT_STRING, Tindices=DT_INT32](Const_86, Const_88, Const_89)]]


In [49]:
indices = tf.constant([
                        [[0,0], [3,0], [2,0], [1,0]]
#                     ,[[1,3], [1,3], [1,2], [1,0]]
                      ])
updates = tf.constant([
                       [[5, 5, 5, 5, 0], 
                        [6, 6, 6, 6, 3],
                        [7, 7, 7, 7, 2], 
                        [8, 8, 8, 8, 1]]
                       
#                      , [[5, 5, 5, 3], 
#                         [6, 6, 6, 3],
#                         [7, 7, 7, 2], 
#                         [8, 8, 8, 0]]
                       ])
shape = tf.constant([4, 4, 5])
print(indices.shape, 'inputs shape', updates.shape, shape.shape)
scatter = tf.scatter_nd(indices, updates, shape)
print('scatter shape is ', scatter.get_shape())
print(scatter.eval())

(1, 4, 2) inputs shape (1, 4, 5) (3,)
scatter shape is  (4, 4, 5)
[[[5 5 5 5 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[8 8 8 8 1]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[7 7 7 7 2]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[6 6 6 6 3]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [43]:
np.set_printoptions(linewidth=100, precision=4)

print(' indcs shape: ',sort_inds.shape)
print(sort_inds.eval())

detection_grid, class_grid, batch_grid = tf.meshgrid( tf.range(num_batches),tf.range(num_classes), tf.range(num_detections) ,indexing='ij')
print('detection_grid', type(detection_grid), 'shape',tf.shape(detection_grid).eval())
print(detection_grid.eval())

print('batch_grid', type(batch_grid), 'shape',tf.shape(batch_grid).eval())
print(batch_grid.eval())

print('class_grid', type(class_grid), 'shape',tf.shape(class_grid).eval())
print(class_grid.eval())


# gather_inds = tf.stack([batch_grid , sort_inds],axis = -1)

# # print('-- stack results ----')
# # print('gather_inds', type(gather_inds), 'shape',tf.shape(gather_inds).eval())
# # print(gather_inds.eval())

# print('a_boxes_3d.shape', tf.shape(a_boxes_3d).eval())
# print(a_boxes_3d.eval())
# # print()

# srtd_boxes = tf.gather_nd(a_boxes_3d, gather_inds)
# print('-- gather_nd results ----')
# print(' srtd_boxes shape : ', tf.shape(srtd_boxes).eval())
# print(srtd_boxes.eval())



 indcs shape:  (3, 28)
[[ 0  1  3  9 11 15 17 18 19 20 21 22 23 24 25 26 27  4  5  8 10 12 13  6  7  2 14 16]
 [ 4  6 11 12 13 17 18 19 20 21 22 23 24 25 26 27 15 16  0  1  2  3  7  9 10  5  8 14]
 [ 2  5 14 17 18 19 20 21 22 23 24 25 26 27 12  4 15  0  1  3  6  7  8  9 10 11 13 16]]
detection_grid <class 'tensorflow.python.framework.ops.Tensor'> shape [ 3  4 28]
[[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]

 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

 [[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
  [2 2 2 2 2 2 2 2 2 2 2 2 2 2